FROM python

ENV TERM=xterm

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get dist-upgrade -y

# Python Requirements

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /bybit_bot

CMD [ "python", "-u", "/bybit_bot/Python/auto_trader.py" ]
